version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: studentapp-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpw
      POSTGRES_DB: studentdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d studentdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: studentapp-backend
    environment:
      DB_HOST: localhost
      DB_PORT: "5432"
<<<<<<< Updated upstream
      DB_USER: appuser
      DB_PASSWORD: secretpw
      DB_NAME: studentdb
=======
      DB_USER: postgres
      DB_PASSWORD: Peam56201
      DB_NAME: golfsystem
>>>>>>> Stashed changes
      PORT: "3000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3000"   # optional: access API directly on http://localhost:3001
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: studentapp-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"     # open the site at http://localhost:8080
    restart: unless-stopped

volumes:
  pgdata:
